name: authhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2
  file_picker: ^5.0.0
  intl: ^0.19.0
  flutter_image_compress: ^1.1.0
  universal_io: ^2.0.4
  cached_network_image: ^3.2.0
  video_player: ^2.2.1
  universal_html: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
